import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import CustomProvider from "./Provider";

export const metadata = {
  title: "Hello Thali",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
       <CustomProvider>
       <main>
        {children}
        </main>
       </CustomProvider>
        <Toaster />
      </body>
    </html>
  );
}
