import StoreProvider from "@/store/StoreProvider";
import "../styles/globals.css";
import { Toaster } from "@/components/ui/toaster";


export const metadata = {
  title: "Hello Thali",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
    <html lang="en">
        <body>
          <main>{children}</main>
          <Toaster />
        </body>
    </html>
    </StoreProvider>
  );
}
